"""
PowerPoint Presentation Generator for Alfred.

Uses python-pptx for creating professional presentations with:
- Custom themes and styling
- Multiple layout templates
- Images and charts support
- Speaker notes
"""

import io
import logging
from typing import Optional

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RgbColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE

logger = logging.getLogger("alfred.presentation")

# Alfred theme colors (matching the XML theme)
COLORS = {
    "dark_bg": (31, 41, 55),      # #1F2937
    "light_bg": (248, 250, 252),  # #F8FAFC
    "accent1": (15, 118, 110),    # #0F766E (teal)
    "accent2": (29, 78, 216),     # #1D4ED8 (blue)
    "accent3": (180, 83, 9),      # #B45309 (amber)
    "accent4": (190, 18, 60),     # #BE123C (rose)
    "accent5": (124, 58, 237),    # #7C3AED (violet)
    "accent6": (5, 150, 105),     # #059669 (emerald)
    "white": (255, 255, 255),
    "black": (0, 0, 0),
}


def create_presentation(
    title: str,
    subtitle: str = "Generated by Alfred",
    slides: Optional[list[dict]] = None,
    theme_color: str = "accent1",
) -> bytes:
    """
    Create a PowerPoint presentation with Alfred styling.

    Args:
        title: Presentation title
        subtitle: Presentation subtitle
        slides: List of slide dicts with 'title' and 'bullets' keys
        theme_color: Color theme key from COLORS dict

    Returns:
        Bytes of the PPTX file
    """
    prs = Presentation()

    # Set widescreen (16:9)
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Get theme color
    primary_color = COLORS.get(theme_color, COLORS["accent1"])

    # Create title slide
    title_slide = prs.slide_layouts[0]  # Title slide layout
    slide = prs.slides.add_slide(title_slide)

    # Set title
    title_shape = slide.shapes.title
    title_shape.text = title
    title_tf = title_shape.text_frame
    title_p = title_tf.paragraphs[0]
    title_p.font.size = Pt(44)
    title_p.font.bold = True
    title_p.font.color.rgb = RgbColor(*COLORS["dark_bg"])

    # Set subtitle
    if subtitle and len(slide.placeholders) > 1:
        subtitle_shape = slide.placeholders[1]
        subtitle_shape.text = subtitle
        subtitle_tf = subtitle_shape.text_frame
        subtitle_p = subtitle_tf.paragraphs[0]
        subtitle_p.font.size = Pt(24)
        subtitle_p.font.color.rgb = RgbColor(*COLORS["accent1"])

    # Add content slides
    slides = slides or []
    for slide_data in slides:
        content_slide = prs.slide_layouts[1]  # Title and Content
        slide = prs.slides.add_slide(content_slide)

        # Set title with accent color
        title_shape = slide.shapes.title
        title_shape.text = slide_data.get("title", "")
        title_tf = title_shape.text_frame
        title_p = title_tf.paragraphs[0]
        title_p.font.size = Pt(36)
        title_p.font.bold = True
        title_p.font.color.rgb = RgbColor(*primary_color)

        # Add bullets
        if "bullets" in slide_data and slide_data["bullets"]:
            body_shape = slide.placeholders[1]
            body_tf = body_shape.text_frame
            body_tf.clear()

            for i, bullet in enumerate(slide_data["bullets"]):
                if i == 0:
                    p = body_tf.paragraphs[0]
                else:
                    p = body_tf.add_paragraph()

                p.text = bullet
                p.font.size = Pt(20)
                p.space_after = Pt(12)
                p.level = 0
                p.font.color.rgb = RgbColor(*COLORS["dark_bg"])

    # Save to bytes
    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output.getvalue()


def create_presentation_from_deck(deck: dict) -> bytes:
    """
    Create presentation from Alfred's deck format.

    Args:
        deck: Dict with 'title', 'subtitle', 'slides' keys

    Returns:
        Bytes of the PPTX file
    """
    return create_presentation(
        title=deck.get("title", "Untitled"),
        subtitle=deck.get("subtitle", "Generated by Alfred"),
        slides=deck.get("slides", []),
    )


def add_image_to_slide(
    slide,
    image_path: str,
    left: float = 2.0,
    top: float = 2.0,
    width: float = 9.0,
) -> None:
    """Add an image to a slide."""
    slide.shapes.add_picture(
        image_path,
        Inches(left),
        Inches(top),
        Inches(width),
    )


def add_chart_to_slide(
    slide,
    chart_type: str,
    data: list[list],
    left: float = 2.0,
    top: float = 2.0,
    width: float = 9.0,
    height: float = 4.0,
) -> None:
    """
    Add a chart to a slide.

    Args:
        slide: pptx Slide object
        chart_type: 'bar', 'line', 'pie', 'column'
        data: 2D list with headers and values
        left, top, width, height: Position and size in inches
    """
    from pptx.chart.data import CategoryChartData
    from pptx.enum.chart import XL_CHART_TYPE

    chart_data = CategoryChartData()

    # First row is categories, subsequent rows are series
    if len(data) < 2:
        return

    categories = data[0]
    series_data = data[1:]

    chart_data.categories = categories
    for i, series in enumerate(series_data):
        chart_data.add_series(f"Series {i + 1}", series[1:])

    chart_type_map = {
        "bar": XL_CHART_TYPE.BAR_CLUSTERED,
        "line": XL_CHART_TYPE.LINE,
        "pie": XL_CHART_TYPE.PIE,
        "column": XL_CHART_TYPE.COLUMN_CLUSTERED,
    }

    xlsx_chart_type = chart_type_map.get(chart_type, XL_CHART_TYPE.COLUMN_CLUSTERED)

    slide.shapes.add_chart(
        xlsx_chart_type,
        Inches(left),
        Inches(top),
        Inches(width),
        Inches(height),
        chart_data,
    )


def add_speaker_notes(slide, notes: str) -> None:
    """Add speaker notes to a slide."""
    notes_slide = slide.notes_slide
    notes_slide.notes_text_frame.text = notes
